---
abstract: 'Create links in one directory for files in another'
author:
  - 'Matthew Musgrove, C<< <mr.muskrat at gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-LinkDir-OO
no_index:
  directory:
    - inc
    - t
requires:
  File::Path: 2.07
  perl: 5.8.0
resources:
  homepage: http://github.com/mrmuskrat/File-LinkDir-OO/tree
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://github.com/mrmuskrat/File-LinkDir-OO.git
version: 1.00_04
